from app.models.enums import Category, Priority

CATEGORY_KEYWORDS: dict[Category, list[str]] = {
    Category.account_access: [
        "login",
        "log in",
        "log-in",
        "sign in",
        "signin",
        "password",
        "reset password",
        "2fa",
        "two-factor",
        "two factor",
        "account locked",
        "locked out",
        "authentication",
        "username",
        "verification code",
        "can't access my account",
    ],
    Category.technical_issue: [
        "error",
        "crash",
        "crashes",
        "crashing",
        "not working",
        "broken",
        "timeout",
        "exception",
        "glitch",
        "freeze",
        "freezes",
        "unresponsive",
        "500 error",
        "won't load",
        "loading forever",
    ],
    Category.billing_question: [
        "payment",
        "invoice",
        "refund",
        "charge",
        "charged",
        "subscription",
        "billing",
        "credit card",
        "receipt",
        "price",
        "overcharged",
        "double charged",
        "cancel my plan",
        "renewal",
    ],
    Category.feature_request: [
        "feature request",
        "enhancement",
        "suggestion",
        "would be nice",
        "please add",
        "could you add",
        "it would be great",
        "improve",
        "add support for",
        "wish list",
    ],
    Category.bug_report: [
        "bug",
        "defect",
        "reproduce",
        "steps to reproduce",
        "reproduction steps",
        "regression",
        "expected behavior",
        "actual behavior",
        "found a bug",
    ],
}

PRIORITY_KEYWORDS: dict[Priority, list[str]] = {
    Priority.urgent: ["can't access", "cannot access", "critical", "production down", "security"],
    Priority.high: ["important", "blocking", "asap"],
    Priority.low: ["minor", "cosmetic", "suggestion"],
}
